import designTokens from '../config/designTokens';

export default {
  name: 'standardTheme',
  global: {
    backgroundColor: designTokens.colors.purple700,
    textAreaSelection: {
      backgroundColor: designTokens.colors.orange400,
    },
  },
  typography: {
    color: {
      primaryInverse: designTokens.colors.grey000,
      primary: designTokens.colors.grey900,
      secondary: designTokens.colors.grey600,
      secondaryInverse: designTokens.colors.purple100,
      highlight: designTokens.colors.purple500,
      highlightInverse: designTokens.colors.orange300,
      success: designTokens.colors.green800,
      warning: designTokens.colors.yellow900,
      error: designTokens.colors.red700,
      disable: designTokens.colors.grey100,
      interactive: designTokens.colors.orange800,
    },
  },
  color: {
    background: {
      primary: designTokens.colors.grey025,
      secondary: designTokens.colors.grey000,
      inverse: designTokens.colors.purple800,
      gradient: designTokens.colors.gradient,
      highlightDark: designTokens.colors.purple600,
      highlight: designTokens.colors.purple400,
      highlightLight: designTokens.colors.purple050,
      success: designTokens.colors.green700,
      warning: designTokens.colors.yellow700,
      error: designTokens.colors.red700,
      successLight: designTokens.colors.green300,
      warningLight: designTokens.colors.yellow300,
      errorLight: designTokens.colors.red300,
      disable: designTokens.colors.grey050,
      header: designTokens.colors.purple600,
      focus: designTokens.colors.purple800,
    },
    divisor: {
      standard: designTokens.colors.grey050,
      inverse: designTokens.colors.purple050,
    },
    icon: {
      standard: designTokens.colors.purple800,
      primary: designTokens.colors.grey000,
      secondaryInverse: designTokens.colors.purple100,
    },
  },
  button: {
    primary: {
      default: designTokens.colors.orange600,
      hover: designTokens.colors.orange400,
      active: designTokens.colors.orange600,
      focusAfter: designTokens.colors.purple800,
      disabledBackground: designTokens.colors.grey200,
      disabledColor: designTokens.colors.grey400,
    },
    secondary: {
      default: designTokens.colors.grey900,
      light: designTokens.colors.grey000,
      hover: designTokens.colors.transparent008,
      hoverLight: designTokens.colors.transparentLight008,
      focusAfter: designTokens.colors.purple800,
      disabledBorder: designTokens.colors.grey200,
      disabledColor: designTokens.colors.grey400,
      disabledColorLight: designTokens.colors.grey100,
    },
    invisible: {
      default: designTokens.colors.purple600,
      light: designTokens.colors.grey000,
      dark: designTokens.colors.grey900,
      hoverDefault: designTokens.colors.purple800,
      hoverLight: designTokens.colors.grey100,
      hoverDark: designTokens.colors.grey800,
      activeDefault: designTokens.colors.purple900,
      activeLight: designTokens.colors.grey000,
      activeDark: designTokens.colors.grey900,
      focusAfter: designTokens.colors.purple800,
      disabled: designTokens.colors.grey200,
    },
    link: {
      standard: designTokens.colors.purple800,
      altColorInverse: designTokens.colors.grey000,
      altColor: designTokens.colors.grey600,
      primary: designTokens.colors.grey600,
      secondary: designTokens.colors.grey000,
    },
    labelHighlight: designTokens.colors.purple600,
  },
  cardShadow: {
    standard: {
      idle: designTokens.shadows.default.idle,
      active: designTokens.shadows.default.active,
      hover: designTokens.shadows.default.hover,
      borderRadius: designTokens.borderRadius.cardShadow,
    },
    inverse: {
      idle: designTokens.shadows.dark.idle,
      active: designTokens.shadows.dark.active,
      hover: designTokens.shadows.dark.hover,
      borderRadius: designTokens.borderRadius.cardShadow,
    },
  },
  textField: {
    textFieldOutline: designTokens.colors.grey100,
  },
  border: {
    primary: designTokens.colors.grey000,
    disable: designTokens.colors.grey100,
    primaryInverse: designTokens.colors.purple200,
    secondaryInverse: designTokens.colors.purple100,
    highlight: designTokens.colors.purple800,
  },
};
